### ISSUE TITLE
ModuleNotFoundError: No module named 'hyperscan._hyperscan'

### ISSUE THREAD

**Issue by h4y0zzz** [darvid/python-hyperscan#56]
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyperscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/hyperscan/__init__.py", line 3, in <module>
    from hyperscan._hyperscan import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'hyperscan._hyperscan'

**Comment by betterlch** [comment]
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import hyperscan
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib/python3.11/site-packages/hyperscan/**init**.py", line 3, in 
> > > > from hyperscan._hyperscan import *  # noqa: F401, F403
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > ModuleNotFoundError: No module named 'hyperscan._hyperscan'

alalysisplatform.jpg

**Comment by shopee2021** [comment]
Type "help", "copyright", "credits" or "license" for more information.

import hyperscan
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python3.11/site-packages/hyperscan/init.py", line 3, in
from hyperscan._hyperscan import * # noqa: F401, F403
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'hyperscan._hyperscan'
